NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GA2VY27NFIC4GO4UPHMEKNPLWQFZODDSXJQNRVOH4OSOZDW5AXSML2NT"
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="VEXONIC ORG"
ORG_URL="https://www.stellarvexonic.com/"
ORG_DESCRIPTION="Play, trade, and earn anytime, anywhere. Vexonic is available on both desktop and mobile devices. Soon on iOS and Android."
ORG_LOGO="https://www.stellarvexonic.com/vexonic_logo.png"


[[CURRENCIES]]
code="VEXONIC"
issuer="GA2VY27NFIC4GO4UPHMEKNPLWQFZODDSXJQNRVOH4OSOZDW5AXSML2NT"
home_domain="https://www.stellarvexonic.com/"
anchor_asset_type="crypto"
anchor_asset="VEXONIC"
name="VEXONIC"
desc="Play, trade, and earn anytime, anywhere. Vexonic is available on both desktop and mobile devices. Soon on iOS and Android."
image="https://www.stellarvexonic.com/vexonic_logo.png"


